sudo: required
services:
  - docker

before_install:
  - docker build -t akash/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akash/docker-react npm run test

deploy:
  provider: elasticbeanstack
  region: "us-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-1-730335592702"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
